export const rulesSchema = {
  devlanguage: [
    "JavaScript",
    "TypeScript",
    "Python",
    "PHP",
    "Java",
    "C#",
    "Go",
    "Ruby",
    "Rust",
    "Kotlin",
    "Swift",
    "Scala",
    "Dart",
    "Elixir",
    "Clojure",
    "Haskell",
  ],
  framework: {
    JavaScript: [
      "React",
      "Vue",
      "Next.js",
      "Angular",
      "Svelte",
      "Vite",
      "Express",
      "Nuxt.js",
      "Gatsby",
      "Remix",
      "Astro",
      "SvelteKit",
    ],
    TypeScript: [
      "React",
      "Vue",
      "Next.js",
      "Angular",
      "Svelte",
      "NestJS",
      "Express",
      "Nuxt.js",
      "Gatsby",
      "Remix",
      "Astro",
      "SvelteKit",
      "tRPC",
    ],
    Python: ["Django", "Flask", "FastAPI", "Pyramid", "aiohttp", "Tornado", "Sanic", "Starlette"],
    PHP: ["Laravel", "Symfony", "CodeIgniter", "Yii", "CakePHP", "Slim", "Lumen"],
    Java: ["Spring", "Hibernate", "Quarkus", "Micronaut", "Jakarta EE", "Vert.x"],
    "C#": [".NET Core", "Blazor", "ASP.NET", "Entity Framework", "Xamarin", "MAUI"],
    Go: ["Gin", "Echo", "Fiber", "Buffalo", "Revel", "Chi", "Beego"],
    Ruby: ["Ruby on Rails", "Sinatra", "Hanami", "Grape"],
    Rust: ["Rocket", "Actix", "Axum", "Warp", "Tide"],
    Kotlin: ["Ktor", "Spring Boot", "Compose", "Android SDK"],
    Swift: ["Vapor", "SwiftUI", "UIKit", "Combine"],
    Dart: ["Flutter", "Angel", "Aqueduct"],
    Scala: ["Play Framework", "Akka", "http4s", "ZIO"],
    Elixir: ["Phoenix", "Nerves", "Absinthe"],
  },
  platform: ["Mobile", "Web", "Desktop", "Hybrid", "Server", "Embedded", "Blockchain", "IoT"],
  styling: [
    "TailwindCSS",
    "ShadCN",
    "Bootstrap",
    "Material-UI",
    "Bulma",
    "Chakra UI",
    "Foundation",
    "Sass/SCSS",
    "Styled Components",
    "Emotion",
    "CSS Modules",
    "PostCSS",
    "Stitches",
    "Vanilla Extract",
    "UnoCSS",
    "WindiCSS",
    "DaisyUI",
    "Radix UI",
    "HeadlessUI",
  ],
  backendplatform: [
    "Firebase",
    "Supabase",
    "AWS Amplify",
    "Azure",
    "Google Cloud",
    "Heroku",
    "DigitalOcean",
    "Cloudflare",
    "Vercel",
    "Netlify",
    "Platform.sh",
    "Railway",
    "Render",
    "Fly.io",
    "Oracle Cloud",
    "IBM Cloud",
    "Linode",
    "Vultr",
  ],
  statemanagement: {
    React: ["Redux", "Context API", "MobX", "Zustand", "Recoil", "Jotai", "XState", "Valtio", "React Query", "SWR"],
    "Next.js": ["Redux", "Context API", "MobX", "Zustand", "Recoil", "Jotai", "XState", "Valtio", "React Query", "SWR"],
    Vue: ["Vuex", "Pinia", "VueUse", "Vue Query"],
    Angular: ["NgRx", "Akita", "NGXS", "RxJS"],
    Svelte: ["Svelte Store", "Svelte Query"],
  },
  database: [
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "SQLite",
    "Redis",
    "DynamoDB",
    "Cassandra",
    "CockroachDB",
    "Fauna",
    "Neo4j",
    "ElasticSearch",
    "MariaDB",
    "Oracle",
    "Microsoft SQL Server",
    "Firebase Realtime Database",
    "PlanetScale",
    "Supabase Database",
    "TiDB",
    "InfluxDB",
    "TimescaleDB",
  ],
  testing: [
    "Jest",
    "Mocha",
    "Pytest",
    "JUnit",
    "RSpec",
    "Cypress",
    "Playwright",
    "Puppeteer",
    "Selenium",
    "Supertest",
    "TestCafe",
    "Vitest",
    "AVA",
    "Tape",
    "WebdriverIO",
    "K6",
    "Artillery",
    "JMeter",
    "Gatling",
    "Locust",
  ],
  deployment: [
    "Vercel",
    "Netlify",
    "AWS",
    "Google Cloud",
    "Azure",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Pulumi",
    "Ansible",
    "Chef",
    "Puppet",
    "Vagrant",
    "Helm",
    "OpenShift",
    "Rancher",
    "Digital Ocean App Platform",
    "Heroku",
  ],
  ci_cd: [
    "GitHub Actions",
    "CircleCI",
    "Jenkins",
    "GitLab CI",
    "Travis CI",
    "Azure Pipelines",
    "Bitbucket Pipelines",
    "TeamCity",
    "Bamboo",
    "Drone CI",
    "GoCD",
    "Argo CD",
    "Flux CD",
    "Spinnaker",
  ],
  logging: [
    "Winston",
    "Morgan",
    "Sentry",
    "Datadog",
    "ELK Stack",
    "Grafana Loki",
    "New Relic",
    "Splunk",
    "Logstash",
    "Fluentd",
    "Vector",
    "Prometheus",
    "Jaeger",
    "Zipkin",
    "OpenTelemetry",
  ],
  auth: [
    "JWT",
    "OAuth 2.0",
    "Firebase Auth",
    "Auth0",
    "Supabase Auth",
    "Okta",
    "Keycloak",
    "Cognito",
    "Clerk",
    "NextAuth.js",
    "Passport",
    "Microsoft Identity",
    "Magic Link",
    "SAML",
    "OpenID Connect",
  ],
};

// Export types for all categories
export type DevLanguage = (typeof rulesSchema.devlanguage)[number];
export type Framework = (typeof rulesSchema.framework)[keyof typeof rulesSchema.framework][number];
export type Platform = (typeof rulesSchema.platform)[number];
export type Styling = (typeof rulesSchema.styling)[number];
export type BackendPlatform = (typeof rulesSchema.backendplatform)[number];
export type StateManagement = (typeof rulesSchema.statemanagement)[keyof typeof rulesSchema.statemanagement][number];
export type Database = (typeof rulesSchema.database)[number];
export type Testing = (typeof rulesSchema.testing)[number];
export type Deployment = (typeof rulesSchema.deployment)[number];
export type CICD = (typeof rulesSchema.ci_cd)[number];
export type Logging = (typeof rulesSchema.logging)[number];
export type Auth = (typeof rulesSchema.auth)[number];

export interface CursorRoles {
  devLanguage: DevLanguage;
  framework?: Framework;
  platform: Platform;
  styling?: Styling[];
  backendPlatform?: BackendPlatform[];
  stateManagement?: StateManagement[];
  database?: Database[];
  testing?: Testing;
  deployment?: Deployment[];
  ci_cd?: CICD[];
  logging?: Logging[];
  auth?: Auth[];
  additionalRules?: string[];
  customRules?: Record<string, unknown>;
}
